### ISSUE TITLE
spacy not imported by default in quick_start.ipynb

### ISSUE THREAD

**Issue by wpnbos** [NorskRegnesentral/skweak#1]
Hi,

Just a little thing, spacy isn't imported by default in quick_start.ipynb, so running the cells top to bottom gives an error. 

Also, `FileNotFoundError: [Errno 2] No such file or directory: 'data/crunchbase_companies.json'` occurs in the gazetteers cell, as crunchbase_companies.json is not actually present in the data directory yet.

**Comment by plison** [comment]
Fixed!
