### ISSUE TITLE
Annotators (sources) issuing annotations after first 1,000 docs not detected

### ISSUE THREAD

**Issue by alfredomg** [NorskRegnesentral/skweak#11]
Hi again,

I found a problem with this method:

```
def _extract_sources(self, docs: Iterable[Doc], max_number=1000):
        """Extract the names of all labelling sources mentioned in the documents
        (and not included in the list of sources to avoid)"""
        sources = set()
        for i, doc in enumerate(docs):
            for source in doc.spans:
                if (len(doc.spans[source]) > 0 and
                        "aggregated" not in doc.spans[source].attrs):
                    sources.add(source)
            if i > max_number:
                break

        return sources
```

It is only called once (from `fit`):

```
sources = self._extract_sources(docs)
```

This means that `sources` will always be collected from the first 1,000 documents in the dataset. I started getting `KeyError`s for some of my annotators as they were triggered only after the first 1,000 documents. So I modified this function to scan the full dataset instead. 

Can I suggest making `max_number` a class parameter or maybe even removing it altogether?

Thanks a lot in advance!

Alfredo

**Comment by plison** [comment]
Yes, you're right, this was a quick hack designed to shorten the time needed to find out all source names, but this can create unnecessary problems. The default value is now set to `None`.
