### ISSUE TITLE
How can I use some manually annotated data as validation data to guide the aggregation step?

### ISSUE THREAD

**Issue by sujoysarkarcs** [NorskRegnesentral/skweak#14]
Hi, can the aggregation step use some validation data like Snorkel?

**Comment by plison** [comment]
Do you mean using validation data to help the algorithm find good parameter values for the aggregation model? 

I think the easiest would be to define the gold standard labels from the validation data as one more labelling function, and then run the aggregation with a very high initial weight for that labelling function (see the argument `initial_weights` when initialising the aggregator).
