### ISSUE TITLE
Skweak for text classification

### ISSUE THREAD

**Issue by nlpravi** [NorskRegnesentral/skweak#22]
Do you have any examples on how to apply skweak for text classification? All the examples I see are for NER. 

Thank you.

**Comment by hiteshpara** [comment]
Hi, @plison I have a quick question,
To find the sentiment of sentences we many many libraries from markets like TextBlob, NLTK, Transformers, Flair...etc.
so when we don't have labeled data to train the sentiment analysis model we can get the labels from those libraries. and then we can train our model.
and how can I get labels to my domain data?
for ex: I have text like "my printer is not working" and I want to label it as "Hardware problem".
How can I achieve this with Skweak? Is there any demo code for that kind of labeling?

**Comment by plison** [comment]
Well, to label your data with domain-specific labels (such as HardwareProblem), you can either write some heuristic rules (such as a rule stating that, if the word "printer" occurs in the sentence, it is likely to be a hardware problem), or have crowdsourcing annotators label those by hand. If you have several of those heuristics / annotators applied to the same texts, you can then use skweak to aggregate their predictions and get a single annotation layer that merges all of them together. Then, the only remaining step is to learn a classical neural classification model (like a language model with a text classification head) based on those aggregated annotations.

**Comment by hiteshpara** [comment]
Thank you much for the answer Lison.
it means that if my I data is domain-specific then I label some labels
manually and create an ML model and use that model in skwaek to label other
samples. if I am not willing to go with heuristic?
how can I get results like Donald trump-person, $700-money like this for
the example given for ner
