### ISSUE TITLE
Text classification on domain data

### ISSUE THREAD

**Issue by hiteshpara** [NorskRegnesentral/skweak#29]
Hi, @plison I have a quick question,
To find the sentiment of sentences we many many libraries from markets like TextBlob, NLTK, Transformers, Flair...etc.
so when we don't have labeled data to train the sentiment analysis model we can get the labels from those libraries. and then we can train our model.
and how can I get labels to my domain data?
for ex: I have text like "my printer is not working" and I want to label it as "Hardware problem".
How can I achieve this with Skweak? Is there any demo code for that kind of labeling?

and how can i get results like Donald trump-person, $700-money like this for the example given?

**Comment by plison** [comment]
See for instance https://github.com/NorskRegnesentral/skweak/blob/main/examples/quick_start.ipynb
