### ISSUE TITLE
Runtime error in display_entities

### ISSUE THREAD

**Issue by latchukarthick98** [NorskRegnesentral/skweak#34]
I am using the latest version of skweak: 0.2.17. I tried running the example (quick-start.ipynb) in the repo. When I try to execute

>  skweak.utils.display_entities(docs[28], "other_org_detector")

, I get this error.

![image](https://user-images.githubusercontent.com/24844434/149867595-a0d1cc18-c8e8-4edd-bb79-8065de83b1c2.png)

**Comment by plison** [comment]
Oops, sorry, that was a mistake on my side when correcting a bug yesterday.

**Comment by latchukarthick98** [comment]
Thank you! It worked. But the same error persists for "Step by step NER" tutorial.
![image](https://user-images.githubusercontent.com/24844434/150012625-85fe54a7-9365-4c0c-8332-7e65753cfc62.png)

**Comment by plison** [comment]
That's odd, from the error message you got, it seems you are not running the very last version (updated yesterday), since the line 740 in utils.py is now "spans = get_spans(doc, [layer]). Could you do a git pull?
