### ISSUE TITLE
HMM and Scores

### ISSUE THREAD

**Issue by hiteshpara** [NorskRegnesentral/skweak#35]
HI,
Thank you for this wonderful library.
I want to know what is the role of HMM here and why we are using it. and after running I am getting some scores like this,
  1         -51.1920             +nan
         2         -51.3015          -0.1095
may I know what this represents?
and also in a research paper(https://arxiv.org/pdf/2104.09683.pdf), there is some scores like this,
HMM-aggregated labels:
- only heuristics 0.62 0.53
- only gazetteers 0.46 0.39
- only NER models 0.60 0.52
- all but doc-level 0.83 0.74
- all labelling functions 0.83 0.75
what does all this score represent and how can I get by code?
can anyone please help me with this ASP? appreciate the help.
Thank You

**Comment by plison** [comment]
The first numbers you referred to come from the EM iterations. At each iteration, we (or, more precisely, `hmmlearn`, which is the library we build upon for the parameter estimation) provide the likelihood of the model with respect to the training data and the evolution of the likelihood with respect to the previous iteration.

The second numbers are F_1 scores (either token or entity-level) computed on the basis of the gold standard data.
