### ISSUE TITLE
HMM.__repr__  crash

### ISSUE THREAD

**Issue by david-waterworth** [NorskRegnesentral/skweak#39]
This is a slightly odd issue, and it's not major but if you construct am `HMM` instance and then type the variable name you get a stack dump. The issue is that HMM is an instance of the sklearn BaseEstimator via `_BaseHMM` and it's `__repr__` expects every class constructor argument to be available as a member variable.

i.e. in jupyter but this should work in a console

```
hmm = aggregation.HMM("hmm", ["DEVICE", "EQUIP", "LOCATION", "POINT"], sequence_labelling=False)
hmm

AttributeError: 'HMM' object has no attribute 'prefixes'
```

SKLearn expects that the following should work:

```
hmm._get_param_names()
hmm.get_params()
```

But you don't save `prefixes` and a number of other arguments, the `BaseEstimator` contains the following:

```
        if sequence_labelling:
            if prefixes not in {"IO", "BIO", "BILUO", "BILOU"}:
                raise RuntimeError(
                    "Tagging scheme must be 'IO', 'BIO', 'BILUO' or ''")
            self.out_labels = ["O"]
            for label in labels:
                for prefix in prefixes.replace("O", ""):
                    self.out_labels.append("%s-%s" % (prefix, label))
        else:
            self.out_labels = labels
```

This is to support hyper-parameter optimisation etc. If you simply add:

```
self.sequence_labelling = sequence_labelling
self.prefixes = prefixes
self.labels = labels
```

It should fix the issue (although to do it "properly" you then need to make self.out_labels a property getter method and move the logic above into it, as technically sklearn can update the params dictionary and you need anything dependent on them to dynamically update)

**Comment by plison** [comment]
This should now be fixed (let me know if it doesn't)
