### ISSUE TITLE
AttributeError: 'HMM' object has no attribute '_do_foward_pass' when calling HMM.fit()

### ISSUE THREAD

**Issue by AlineBornschein** [NorskRegnesentral/skweak#41]
_do_forward_pass() seems to have been deprecated from new version of hmmlearn. After downgrading hmmlearn to version 0.2.6 the error is resolved.

**Comment by david-waterworth** [comment]
I think this is a duplicate of https://github.com/NorskRegnesentral/skweak/issues/38
