### ISSUE TITLE
Trying to run the quick_start code and getting a problem. 

### ISSUE THREAD

**Issue by bhakti-bhatt** [NorskRegnesentral/skweak#46]
Hi there, I am trying to run the code in the quick_start.ipynb file and getting the following error: OSError: [E053] Could not read config file from /usr/local/lib/python3.7/dist-packages/en_core_web_sm/en_core_web_sm-2.2.5/config.cfg

The solution online recommends to downgrade the version for spacy from 3.2.3 to 2.3.5 as a workaround for the above error, however when I try it the function spans in spacy library is not available in a version <3.0. 

I would appreciate any insight in resolving this error. 

Thank you!

**Comment by plison** [comment]
Yes, `skweak` requires at least Spacy v3. You should upgrade your language model `en_core_web_sm` to the newest version -- for instance by removing the language model and installing it again.
