### ISSUE TITLE
ValueError: Cannot apply_along_axis when any iteration dimensions are 0

### ISSUE THREAD

**Issue by bhakti-bhatt** [NorskRegnesentral/skweak#50]
Sentiment Analysis Code is not working due to the above mentioned error.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-30-a0b8eede52ad>](https://localhost:8080/#) in <module>()
      4 #docs = [d for d in train_pred if any([v for (k,v) in d.spans.items()])]
      5 
----> 6 unified_model.fit(train_pred)
      7 
      8 unified_model.annotate_docbin("train_pred.docbin", "train_pred.docbin")

4 frames
[/usr/local/lib/python3.7/dist-packages/skweak/aggregation.py](https://localhost:8080/#) in fit(self, docs, **kwargs)
     85 
     86         obs_generator = (self.get_observation_df(doc) for doc in docs)
---> 87         self._fit(obs_generator, **kwargs)
     88 
     89 

[/usr/local/lib/python3.7/dist-packages/skweak/generative.py](https://localhost:8080/#) in _fit(self, all_obs, cutoff, n_iter, tol)
     95 
     96         # And add the counts from majority voter
---> 97         self._add_mv_counts(all_obs)
     98 
     99         # Finally, we postprocess the counts and get probabilities

[/usr/local/lib/python3.7/dist-packages/skweak/generative.py](https://localhost:8080/#) in _add_mv_counts(self, all_obs)
    417 
    418             # And aggregate the results
--> 419             agg_array = mv.aggregate(obs).values
    420 
    421             if len(agg_array)==0:

[/usr/local/lib/python3.7/dist-packages/skweak/voting.py](https://localhost:8080/#) in aggregate(self, obs)
     51             return np.bincount(x[x>=0], weights=weights[x>=0], 
     52                                minlength=len(self.observed_labels)) 
---> 53         label_votes = np.apply_along_axis(count_fun, 1, obs.values).astype(np.float32)
     54 
     55         # For token-level sequence labelling, we need to normalise the number

<__array_function__ internals> in apply_along_axis(*args, **kwargs)

[/usr/local/lib/python3.7/dist-packages/numpy/lib/shape_base.py](https://localhost:8080/#) in apply_along_axis(func1d, axis, arr, *args, **kwargs)
    376         raise ValueError(
    377             'Cannot apply_along_axis when any iteration dimensions are 0'
--> 378         ) from None
    379     res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
    380 

ValueError: Cannot apply_along_axis when any iteration dimensions are 0

**Comment by plison** [comment]
Could you repost the python code you were trying to run? It's a bit difficult for me to understand what was exactly run from your post.
