### ISSUE TITLE
Pattern for combining Gazetters and Heuristics for the same label

### ISSUE THREAD

**Issue by udayankumar** [NorskRegnesentral/skweak#52]
In my problem space, I want to build a labeling function that combines a list (gazetters) and a Heuristic annotators for the same label. Currently, if I apply them both as independent annotators operations, the last annotators clears all the previous labels because of this [code line](https://github.com/NorskRegnesentral/skweak/blob/main/skweak/base.py#L85).

Is there a suggested pattern that I can utilize to combine multiple annotators for the same label that keeps the previous labels?

**Comment by plison** [comment]
Not sure I understand what you are trying to do. Even though two annotators may generate predictions for the same label, they still need different names to be able to tell them apart. So, make sure the gazetteer and the heuristic have different names.
If you still have problems, could you show me the piece of code you are trying to run?

**Comment by udayankumar** [comment]
Thank you. I got confused with the name and label for the annotators.
