### ISSUE TITLE
heuristics.VicinityAnnotator l Money Detector

### ISSUE THREAD

**Issue by fernandonjardim** [NorskRegnesentral/skweak#55]
Hi There!

[On this page](https://github.com/NorskRegnesentral/skweak/wiki/Step-1:-Labelling-functions), under the section  "heuristics.VicinityAnnotator" on the given example below, you talk about cue words to be next to proper names, but on the formula, you add "money_detector2" as an argument of the "VicinityAnnotator". Could you explain me why, as money_detector1 has nothing to do with proper names?

```
# Typically, entities next to words like say/tell/listen etc. will be PERSON
cue_words = ["say", "indicate", "reply", "claim", "declare", "tell", "answer", "listen"]
VicinityAnnotator("money_detector2", {word:"PERSON" for word in cue_words}, "nnp_detector", max_window=2)
```

Super thanks in advance!

**Comment by plison** [comment]
You're right, that was an error on my part. The first argument of labelling functions is typically always the name of the function. It's now corrected :-)

**Comment by fernandonjardim** [comment]
Awesome, super thanks, you rock ((:
