### ISSUE TITLE
CASED AND UNCASED GAZETTEERS ON PIPE

### ISSUE THREAD

**Issue by fernandonjardim** [NorskRegnesentral/skweak#59]
Hi there, 

I am [following this tutorial](https://github.com/NorskRegnesentral/skweak/blob/main/examples/ner/Step%20by%20step%20NER.ipynb), but I am not managing to adapt it to a pipe of docs. 

For instance, this part of the code: `annotator2(annotator(doc))` is where you add the cased to the uncased (or vice versa) right ?

What would it be the version of it, when we don't have a single doc, but a pipe of corpus? 

I've tried all the variations of this:

```
docs = list(gazetteer2(gazetteer1).pipe(docs_retrieval))
docs = list(gazetteer2.gazetteer1.pipe(docs_retrieval))
docs = list(gazetteer2.pipe(gazetteer1(docs_retrieval)))
docs = list(gazetteer2.pipe((gazetteer1(docs_retrieval))))
```

but no luck //:

Any help? (:

**Comment by plison** [comment]
I think the correct answer should be:

```python
docs = list(gazetteer2.pipe(gazetteer1.pipe(docs_retrieval)))
```

Or, in a more readable way:
```python
docs = gazetteer1.pipe(docs_retrieval)
docs = gazeteer2.pipe(docs)
docs = list(docs)
```

**Comment by fernandonjardim** [comment]
You rock, thanks !
