### ISSUE TITLE
Link / Source not working

### ISSUE THREAD

**Issue by fernandonjardim** [NorskRegnesentral/skweak#60]
Hi there!

I [am following this tutorial](https://github.com/NorskRegnesentral/skweak/blob/main/examples/ner/Step%20by%20step%20NER.ipynb), and this [link is broken](https://github.com/NorskRegnesentral/skweak/releases/download/v0.2/wikidata_tokenised.json.gz).

It is on the item 2.1 on WIKIDATA

**Comment by plison** [comment]
Thanks, it's now corrected!
