### ISSUE TITLE
Error Importing import examples.ner.conll2003_ner

### ISSUE THREAD

**Issue by fernandonjardim** [NorskRegnesentral/skweak#61]
Hi There!

As you probably know, I am [following this tutorial](https://github.com/NorskRegnesentral/skweak/blob/main/examples/ner/Step%20by%20step%20NER.ipynb), so I am trying to import `examples.ner.conll2003_ner`.

I've copied the file to the same folder as my colab, changed the notebook's directory to also be in the same directory, and when Importing, I am getting the error below:

![image_2022-06-03_225354627](https://user-images.githubusercontent.com/31636793/171959109-4e108f41-0291-46b9-9656-5a300a2e66df.png)

Do you know what can be happening?

Without it, I cannot also run the ```full_annotator = examples.ner.conll2003_ner.NERAnnotator().add_all()``` /:

**Comment by plison** [comment]
You have probably downloaded the conll2003_ner.py file as a web page (from GitHub) instead of Python file. I would recommend to download all files by cloning the directory (`git clone ...`) instead of downloading file by hand.
