### ISSUE TITLE
Functionality to construct the detected span from start and end index

### ISSUE THREAD

**Issue by katreparitosh** [NorskRegnesentral/skweak#63]
Hi team,

Thanks for creating such a useful framework - works efficiently for NER tasks.

I was wondering if there is any function which constructs the detected span from the returned start and end index?

Example: 

```
Sentence: "I work at XYZ",
Returns: 'spans': {'start': 8, 'end': 11, 'label': 'COMPANY'}
```

Essentially, the function returns `'XYZ'` also along with the above information.

I went through the code, but I did not find any. If not available, can you help on how it can be constructed? This function will help to review the labels and performance quickly in bulk.

Thanks!

**Comment by plison** [comment]
Yes, you can use the function `utils.get_spans` to get all spans. Then, for each span, you can get the character-level offsets from `span.start_char` and `span.end_char`, and the label from `span.label_`.

Hope it helps!
