### ISSUE TITLE
Error in MultilabelNaiveBayes

### ISSUE THREAD

**Issue by sujeethrv** [NorskRegnesentral/skweak#67]
![image](https://user-images.githubusercontent.com/87650861/176379005-a72ea0d0-86e2-4c02-8195-938dc0e0b177.png)

I am using Skweak Multilabel for classification and I am getting the following error message - **RuntimeError: No valid state found at position 0** 

I aggregated LFs using CombinedAnnotator, then initialized MultilabelNaiveBayes - **MultilabelNaiveBayes("skweak_preds",final_label_list)** and then trained the model - **skweak_model.fit(d2s)** 

Any help in fixing this is appreciated. Thanks!

**Comment by mnschmit** [comment]
This seems to be the same (or similar) kind of error I ran into (#43). We didn't really manage to pinpoint the exact source of the problem at that time.
One workaround that worked for me was replacing `-np.inf` by a large negative number. But if you can help trace down why this sometimes happens and sometimes doesn't, it would be great, too!

**Comment by plison** [comment]
Could you send a minimal data example, so I can have a look at it?
Typically, when this happens, it means that the HMM has reached a position where no state is possible (all values have a probability of zero), given the current transition and emission probabilities.

**Comment by kavyaReddy1729** [comment]
> Could you send a minimal data example, so I can have a look at it? Typically, when this happens, it means that the HMM has reached a position where no state is possible (all values have a probability of zero), given the current transition and emission probabilities.

example:  
Sentence:    Eastern Equine Encephalitis Virus (EEEV) is a dangerous disease

we have predicted labels before from 2 models.
model1:  ["negative", "not safe"]
model2: ["positive", "not safe"]

how to generate a labelling function for this kind of multi labelling.

**Comment by ayoub-chammam** [comment]
same error occured to me while working on an NER Task with the train set from the CoNLL dataset.

**Comment by plison** [comment]
Ok, I found what was going on (and sorry for the answering delay): even though the aggregation model allows for multi-label predictions, `skweak` still assumes that each _labelling source_ only provides a single label for a given text. In other words, the aggregator may predict multiple labels, but each labelling source must stick to one single label at a time.

Fortunately, there is an easy way to change your code: just create a separate labelling source for each possible label outputted by a given model, like `model1_negative`, `model1_positive`, `model1_not_safe`, etc.
