### ISSUE TITLE
Custom NER model training

### ISSUE THREAD

**Issue by RuofanYu95** [NorskRegnesentral/skweak#70]
Hi, I'm wondering if there's any NER model that could be trained using probabilistic labels after aggregation, like the discriminative model used in Snorkel?  Here we only use the label with the highest posterior probability as true label, the probability of being other labels is not used.

**Comment by plison** [comment]
Yes, in the document spans you can find the probabilities produced by the model in the attribute "probs":
```doc.spans[name_of_your_aggregator].attrs["probs"]```

You can then train your favorite machine learning model from those probabilistic labels.

**Comment by RuofanYu95** [comment]
Thanks for the explanation!
