### ISSUE TITLE
minimal example not working

### ISSUE THREAD

**Issue by davidbetancur8** [NorskRegnesentral/skweak#73]
When I try to run the minimal example on the home page, an error appears:
AttributeError: 'BaseHMM' object has no attribute '_do_forward_log_pass'

Am I missing something from the install or is it just pip install skweak?

**Comment by nleguillarme** [comment]
I just ran into the same problem with a fresh install of skweak.
It seems that the problem is with the new version of hmmlearn==0.2.8.
Everything works just fine with hmmlearn==0.2.7.

**Comment by plison** [comment]
Yes indeed, it seems that the `hmmlearn` API has changed again. The easiest is to indeed downgrade to 0.2.7.

**Comment by plison** [comment]
I think the issue should be resolved by now, but let me know if you still encounter problems!
