### ISSUE TITLE
How to use the already available Label Matrix to train Skweak?

### ISSUE THREAD

**Issue by anjani-dhrangadhariya** [NorskRegnesentral/skweak#76]
I already have some custom labelling functions that label a dataset with binary labels (0, 1). In short, I have a label matrix with a couple of 100 labelling function (LF) labels. How can I use these with Skweak without re-designing or transforming my already available LFs? 

In the minimal Skweak example, this statement `doc = lf3(lf2(lf1(doc)))` applies all the LFs to the `doc` object. However, inspecting the `doc` object does not show how the LF 1, 2, and 3 labels are stored or am I missing how to extract this information from the `doc` object? If it could be identified, I can transform my label matrix to this format and train Skweak to predict labels.

**Comment by plison** [comment]
Hi! The results of the labelling functions are stored in `doc.spans`. For instance, the annotations from lf3 will be in `doc.spans["lf3"]`, expressed as a list of labelled text spans (see https://spacy.io/api/spangroup for details).
