### ISSUE TITLE
Adding to the gazetteer annotator constrains

### ISSUE THREAD

**Issue by Astromis** [NorskRegnesentral/skweak#79]
Hi.
First off, thanks for the awesome library.

Faced with the next case. I have a gazetteer annotator that works pretty well, but sometimes words from this gazetteer collide with unrelated words. I would like to make a constraint like, for instance, "if the doc has one of these predefined words, so that particular match shouldn't be applied". Or maybe make it like post annotation check. The issue is that all annotators can only add a new label or modify it to another one but not delete, as far as I understand. 

Could you provide some thought how it can be done?

**Comment by plison** [comment]
Sorry for the answering delay. The easiest is probably to make your own, custom gazetteer, for instance by extending the `GazetteerAnnotator` class, and introducing the constraints you wish to enforce there.
