### ISSUE TITLE
hmmlearn 0.3.0

### ISSUE THREAD

**Issue by RXminuS** [NorskRegnesentral/skweak#82]
It'd be great if we could upgrade the hmm-learn dependency to 0.3.0 so that it works with Mac ARM architecture out of the box.

Just looking at the code and the changelog it's a bit overwhelming, but maybe if someone more experienced could help me figure out what's changed I can try and put a PR together.

**Comment by plison** [comment]
I think the issue should be resolved by now, but let me know if you still encounter problems!
